### ISSUE TITLE
Support text extraction

### ISSUE THREAD

**Issue by viezel** [urish/pdfium-wasm#2]
Would it be possible to extract text per page?

**Comment by urish** [comment]
Theoretically yes, but seems like some more work will be needed, see the discussion at #3

**Comment by viezel** [comment]
have you seen these projects? Might be some quick wins. 
 
https://github.com/tojocky/node-pdfium 
https://github.com/viezel/PdfiumAndroid/blob/master/src/main/jni/src/mainJNILib.cpp#L303-L320

**Comment by urish** [comment]
Yea, I think if we get #4 to work, the 2nd link should be pretty straightforward to port

**Comment by viezel** [comment]
great
